const classes = {
  root: [
    'flex',
    'items-center',
    'gap-1',
    'p-1',
    'rounded-shape-1',
    'text-card-contrast',
    'bg-card',
    'border',
    'outline-0',
    'shadow-sm',
    'transition-color',
  ],
  separator: 'w-px h-6 mx-1 bg-border transition',
  item: [
    'inline-flex',
    'items-center',
    'gap-2',
    'px-2',
    'text-sm/8',
    'outline-0',
    'rounded-shape',
    'select-none',
    '[&_svg]:size-4',
    'focus:bg-highlight/50',
    'active:bg-highlight',
    'disabled:opacity-50',
    'aria-disabled:opacity-50',
    'aria-expanded:bg-highlight/50',
    'data-highlight:bg-highlight/50',
  ],
};

export default classes;
